[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"

[[redirects]]
  from = "/sw.js"
  to = "/assets/sw.js"
  status = 200

[[redirects]]
  from = "/assets/sw-*.js"
  to = "/assets/sw.js"
  status = 200 