[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/assets/sw-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"
    Service-Worker-Allowed = "/"

[[redirects]]
  from = "/sw.js"
  to = "/assets/sw-:splat.js"
  status = 200
  force = true 