[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/js/**/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/config/firebase.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add headers for CSS files
[[headers]]
  for = "/styles/**/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

# Make sure CSS and other assets are served correctly
[[redirects]]
  from = "*.css"
  to = ":splat.css"
  status = 200
  force = true

[[redirects]]
  from = "/styles/components/auth.css"
  to = "/styles/components/auth.css"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/init"
  to = "/.netlify/functions/auth-init"
  status = 200
  force = true

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

# Explicitly serve JS files directly
[[redirects]]
  from = "/js/config/app-config.js"
  to = "/js/config/app-config.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/config/firebase.js"
  to = "/js/config/firebase.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/services/authService.js"
  to = "/js/services/authService.js"
  status = 200
  force = true

# Add redirects for CSS files
[[redirects]]
  from = "/styles/*"
  to = "/styles/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/styles/components/*"
  to = "/styles/components/:splat"
  status = 200
  force = true

# Explicit redirects for Firebase diagnostic pages
[[redirects]]
  from = "/firebase-diagnostic.html"
  to = "/firebase-diagnostic.html"
  status = 200
  force = true

[[redirects]]
  from = "/firebase-test.html"
  to = "/firebase-test.html"
  status = 200
  force = true

# The catch-all redirect should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 