[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/sw-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-store"
    Service-Worker-Allowed = "/"

[[redirects]]
  from = "/sw.js"
  to = "/assets/sw-ki5AU8Ys.js"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/assets/:splat"
  status = 200 