[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/js/**/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/config/firebase.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/auth/init"
  to = "/.netlify/functions/auth-init"
  status = 200
  force = true

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

# Explicitly serve JS files directly
[[redirects]]
  from = "/js/config/app-config.js"
  to = "/js/config/app-config.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/config/firebase.js"
  to = "/js/config/firebase.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/services/authService.js"
  to = "/js/services/authService.js"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 