[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/icons/*"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000" 