name: 拽砖转 拽
description: 驻住 驻转 拽砖转 砖转
title: "[拽砖转 拽]: "
labels: [" 砖"]
body:
  - type: input
    id: client-name
    attributes:
      label: 砖 拽
      description:   转 砖  砖 专
      placeholder: 砖专 砖专
    validations:
      required: true
      
  - type: dropdown
    id: request-type
    attributes:
      label: 住 拽砖
      description:  住 拽砖?
      options:
        - 
        - 驻转
        - 
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 专转 驻转
      description:  专转 驻转 砖 拽砖?
      options:
        - 
        - 转
        - 
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 转专 拽砖
      description:  驻专 转 拽砖
      placeholder: 驻专 ...
    validations:
      required: true
      
  - type: textarea
    id: attachments
    attributes:
      label: 拽爪 爪专驻
      description: 转 爪专祝 转转 注  专专转 专 
      placeholder: 专专 拽爪 ...
